name: Manual Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      tag_name:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4