name: Manual Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Give the tag name as v1"
      your_name:
      your_father name:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4