name: Manual Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Give the tag name as v1"
        required: true
      name:
        description: "Give your full name"
        required: true
      father name:
        description: "GIve the full name"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run the command on ubuntu
        run: | 
            echo "Hi I am Aradhya TS" 
            echo "Tag_name: ${{inputs.tag_name}}" 
            echo "Father-name: ${{inputs.father_name}}"